#!/usr/bin/env python3
"""Bundle a saved trace into the viewer so it works with no file to hand.

The bundled trace is a real measured one, not a constructed illustration. A
teaching example that was drawn by hand would belong in a separately labelled
demo (SPEC.md section 10), not in the viewer's default view.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """/* A real saved trace, bundled so the viewer works with no file to hand.
 * Generated by: python -m switchback trace --mode greedy --gamma 4
 * Regenerate with: python scripts/bundle_example_trace.py
 */
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "trace", type=Path, nargs="?", default=Path("artifacts/traces/greedy_g4.jsonl")
    )
    parser.add_argument("--out", type=Path, default=Path("viewer/example-trace.js"))
    args = parser.parse_args()
    text = args.trace.read_text(encoding="utf-8")
    args.out.write_text(
        HEADER + "window.SWITCHBACK_EXAMPLE_TRACE = " + json.dumps(text) + ";\n",
        encoding="utf-8",
    )
    print(f"  bundled {args.trace} into {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
